[package]
authors = ["nokaa <nokaa@cock.li>"]
name = "hayaku-path"
version = "0.1.0"

[dependencies]
log = "0.3.6"
quick-error = "1.1.0"
regex = "0.2"
serde = "0.8.20"
serde_derive = "0.8.19"
serde_json = "0.8.3"

[dependencies.hayaku-http]
git = "https://github.com/hayaku-rs/hayaku-http.git"
